env:
  open:
    STORAGE: local
    DISABLE_API: false

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 8Gi

securityContext:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - name:
      tls: true
      tlsSecret: chartmuseum-tls
